name: Build Executables

# Manueller Trigger
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    # Install Tkinter dependencies for Linux
    - name: Install Tkinter dependencies (Linux only)
      if: runner.os == 'Linux'
      run: sudo apt-get install python3-tk -y

    # Set up Python on all platforms
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas numpy opcua

    # Build executable for each OS
    - name: Build executable for Windows
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed main.py
        mv ./dist/main.exe ./dist/TestbenchManager_windows.exe

    - name: Build executable for macOS
      if: runner.os == 'macOS'
      run: |
        pyinstaller --onefile --windowed --target-arch universal2 main.py
        mv ./dist/main ./dist/TestbenchManager_macos

    - name: Build executable for Linux
      if: runner.os == 'Linux'
      run: |
        pyinstaller --onefile --windowed main.py
        mv ./dist/main ./dist/TestbenchManager_linux

    # Upload executable as artifact for each OS
    - name: Upload executable for Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: TestbenchManager_windows
        path: ./dist/TestbenchManager_windows.exe

    - name: Upload executable for macOS
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v3
      with:
        name: TestbenchManager_macos
        path: ./dist/TestbenchManager_macos

    - name: Upload executable for Linux
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: TestbenchManager_linux
        path: ./dist/TestbenchManager_linux
